[server]
name = "admin"
env = "test"
addr = "127.0.0.1:8000"

[mysql]
addr = "127.0.0.1:3306"
writeDSN = "test:test@tcp(127.0.0.1:3306)/test?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
readDSN = ["test:test@tcp(127.0.0.1:3306)/test?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
active = 20
idle = 10
idleTimeout = "4h"

[redis]
name = "test"
proto = "tcp"
addr = "127.0.0.1:6379"
active = 10
idle = 10
idleTimeout = "10s"
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
expire = "720h"
